tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y util-linux libncurses5-dev libncursesw5-dev gcc g++ binutils bzip2 \
        flex python3 perl make grep diffutils unzip subversion libz-dev libc-dev rsync python2 \
        libxml-parser-perl kmod cpio device-tree-compiler libarchive-zip-perl libc6-i386 lib32stdc++6
      exit
  - command: |
      mkdir build
      cd build
      wget https://toolchains.bootlin.com/downloads/releases/sources/gawk-4.2.1/gawk-4.2.1.tar.xz
      tar axf gawk-4.2.1.tar.xz
      cd gawk-4.2.1
      ./configure --prefix=/usr --libexecdir=/usr/lib
      make -j$(nproc)
      make install
      cd ../..
      git clone https://github.com/QSI01/HVLRS
      cd HVLRS/OpenWRT-LEDE
      patch -p1 < ../../gcc9.patch
      ./scripts/build.sh hvlrs build 1.1.0.6 1.1.0.6
      